<a href="https://colab.research.google.com/github/imy0ung/AI_Basic_Study/blob/main/model/linear_regression_file_input.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/myunghakLee/data.git

Cloning into 'data'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 28.74 KiB | 3.19 MiB/s, done.


In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
import numpy as np
import pandas as pd

In [13]:
xy = np.loadtxt('/content/data/data-01-test-score.csv',delimiter=',',dtype=np.float32) # np의 loadtxt는 숫자형만 읽음
x_data = xy[:,0:-1]
y_data = xy[:,-1]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

x_data = torch.from_numpy(x_data)
y_data = torch.from_numpy(y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25,) [152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.]


In [28]:
class LinearModel(nn.Module) :
  def __init__(self) :
    super().__init__()
    self.linear = nn.Linear(3,1,bias=True)

  def forward(self,x) :
    return self.linear(x)

In [65]:
model = LinearModel()

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = 0.00005)
epochs = 1000

In [70]:
for step in range(epochs) :
  prediction = model(x_data)
  loss = criterion(prediction,y_data)

  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

  if step % 10 == 0 :
    print (f"epoch : {step}, loss : {loss.item():.4}")

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([25])) that is different to the input size (torch.Size([25, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


epoch : 0, loss : 1.056e+03
epoch : 10, loss : 1.056e+03
epoch : 20, loss : 1.056e+03
epoch : 30, loss : 1.056e+03
epoch : 40, loss : 1.056e+03
epoch : 50, loss : 1.056e+03
epoch : 60, loss : 1.056e+03
epoch : 70, loss : 1.056e+03
epoch : 80, loss : 1.056e+03
epoch : 90, loss : 1.056e+03
epoch : 100, loss : 1.056e+03
epoch : 110, loss : 1.056e+03
epoch : 120, loss : 1.056e+03
epoch : 130, loss : 1.056e+03
epoch : 140, loss : 1.056e+03
epoch : 150, loss : 1.056e+03
epoch : 160, loss : 1.056e+03
epoch : 170, loss : 1.056e+03
epoch : 180, loss : 1.056e+03
epoch : 190, loss : 1.056e+03
epoch : 200, loss : 1.056e+03
epoch : 210, loss : 1.056e+03
epoch : 220, loss : 1.056e+03
epoch : 230, loss : 1.056e+03
epoch : 240, loss : 1.056e+03
epoch : 250, loss : 1.056e+03
epoch : 260, loss : 1.056e+03
epoch : 270, loss : 1.056e+03
epoch : 280, loss : 1.055e+03
epoch : 290, loss : 1.055e+03
epoch : 300, loss : 1.055e+03
epoch : 310, loss : 1.055e+03
epoch : 320, loss : 1.055e+03
epoch : 330, loss : 1

In [67]:
print(model(torch.Tensor([[96.,93.,95.]])))

tensor([[185.7888]], grad_fn=<AddmmBackward0>)
