<a href="https://colab.research.google.com/github/imy0ung/AI_Basic_Study/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy**



*   행렬 계산을 위한 파이썬의 외부 라이브러리
*   복잡한 행렬계산, 선형대수, 통계 등의 기능 제공
*   Matlab 행렬 계산 기능과 유사


In [4]:
# 모듈 import
import numpy as np

# 버전 체크
print(np.__version__)
print(np.__name__)

1.25.2
numpy


In [8]:
# Numpy는 list가 아닌 ndarray을 사용함
# list와 다르게 고성능 수치 계산이 가능, 인공지능에서 매우 유용

myarray = np.array([1,2,3])
print(myarray)
print(type(myarray))

[1 2 3]
<class 'numpy.ndarray'>


## **행렬의 정보 확인하기**



1. ndim
2. shape
3. dtype
4. size


In [85]:
# n차원 matrix도 가능
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

2
(3, 3)
int64
9


In [86]:
#1 ndim : 배열의 차원
print(myarray.ndim)

2


In [87]:
#2 shape : 크기 확인
print(myarray.shape)

(3, 3)


In [88]:
#3 dtype : 타입 확인
print(myarray.dtype)

int64


In [89]:
#4 size : 총 요소의 수
print(myarray.size)

9


# **행렬 생성 및 조작**

> 업데이트 중 (2024.07.22)



1. arange
2. linspace
3. zeros, ones, full
4. eye
5. reshape
6. transpose
7. flatten





In [84]:
#1 arange : range()와 유사, 범위를 통해 array 생성
arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(2,10)
print(arr2)

arr3 = np.arange(1,10,2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [78]:
#2 linspace : 수의 범위를 균일하게 나누고자 할 때 사용
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [79]:
#3 zeros, ones, full
print(np.zeros(shape=(3,5)))
print(np.ones(shape=(3,5),dtype = int))
print(np.full(shape=(3,5),fill_value=7))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [80]:
#4 eye : 항등 행렬
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [81]:
#5 reshape : 행렬의 형태 변경
arr4 = np.arange(15)
print(arr4.reshape(3,5))
print(arr4.reshape(3,-1)) # -1은 자동으로 계산
print(arr4.reshape(-1,3))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [82]:
#6 transpose : 전치 행렬
arr5 = np.arange(15).reshape(3,5)
print(arr5)
print(arr5.T)
print(arr5.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [83]:
#7 flatten : 1차원으로 변경
arr6 = np.arange(15).reshape(3,5)
print(arr6)
print(arr6.ravel())
print(arr6.flatten())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# **행렬 연산**

1.  element-wise-operations
2.  broadcasting
3.  matrix 곱셈
4.  boolean indexing
5.  fancy indexing
6.  배열 참조
7.  where

In [69]:
#1 element-wise operations : 행렬끼리의 연산, shape가 맞아야 함
x = np.array([[10,20],[30,40]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x//y)


x = np.array([[1,2,3],[3,4,5]])
y = np.array([1, 2])
# print(x+y) error! shape이 안맞음

[[10 20]
 [30 40]]
[[5 6]
 [7 8]]
[[15 26]
 [37 48]]
[[ 5 14]
 [23 32]]
[[ 50 120]
 [210 320]]
[[2.         3.33333333]
 [4.28571429 5.        ]]
[[0 2]
 [2 0]]
[[2 3]
 [4 5]]
[[11 12 13]
 [13 14 15]]
[[ 1  4  9]
 [ 9 16 25]]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
[[19 22]
 [43 50]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]
[100 101 102 103 104 105 106 107 108 109]
[100 102 105]
[99  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5]
[1.1 2.2 1.3 1.4 2.5]
[[-1.07746533  0.23848917  1.67960037 -1.30580313]
 [-1.13889525 -0.78464639  0.7953204   1.64950807]
 [-0.91948541  2.02837484  0.23634688 -0.46335828]
 [-1.73197305 -0.61783601  1.7104376  -0.05634082]]
[['음수' '양수' '양수' '음수']
 ['음수' '음수' '양수' '양수']
 ['음수' '양수' '양수' '음수']
 ['음수' '음수' '양수' '음수']]


In [71]:
#2 broadcasting : 모든 요소에 대해 연산
x = np.array([[1,2,3],[3,4,5]])
print(x+10)
print(x**2)
print(np.sqrt(x))

[[11 12 13]
 [13 14 15]]
[[ 1  4  9]
 [ 9 16 25]]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [72]:
#3 matrix 곱셈
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a@b)

[[19 22]
 [43 50]]


In [73]:
#4 boolean indexing : boolean 형태로 masking해서 해당 값에 맞는 걸 꺼내올 수 있음
arr = np.arange(1,13).reshape(3,4)
print(arr)
print(arr>5) # masking
print(arr[arr>5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


In [74]:
#5 fancy indexing : array 안에 list을 넣을 수 있음
arr = np.arange(100,110)
print(arr)
idx = [0,2,5]
print(arr[idx])

[100 101 102 103 104 105 106 107 108 109]
[100 102 105]


In [75]:
#6 배열 참조 : 행렬연산을 할 때, python의 값 참조에 대해 유의해야함
a = np.arange(1,13)
a1 = a[:5]
a1[0] = 99 # 같은 값을 참조하기에, a도 바꿈

print(a)
print(a1)

a = np.arange(1,13)
a1 = a[:5].copy() # 방지하려면 copy을 이용
a1[0] = 99

print(a)
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5]


In [76]:
#7 where : np.where(조건, 참인 경우 배열, 거짓인 경우 배열)
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(np.where(cond, xarr, yarr))

a = np.random.randn(4, 4)
print(a)
print(np.where(a > 0, '양수', '음수'))

[1.1 2.2 1.3 1.4 2.5]
[[-1.06029955 -1.82207837 -1.21117645  1.48492015]
 [ 0.74102732  0.71157801  0.29822755  0.46437133]
 [ 0.11822163  1.94369786  2.42320729 -1.26530807]
 [-0.02627203 -1.92754197  0.56080222  0.24663925]]
[['음수' '음수' '음수' '양수']
 ['양수' '양수' '양수' '양수']
 ['양수' '양수' '양수' '음수']
 ['음수' '음수' '양수' '양수']]


# **통계**

1.  axis
2.  sum
3.  mean
4.  min, max
5.  var,std

In [62]:
#1 axis : 0은 행, 1은 열
arr = np.arange(1,13).reshape(3,4)

In [63]:
#2 sum
print(arr)
print(arr.sum())
print(arr.sum(axis=0)) # 행기준으로 덧셈
print(arr.sum(axis=1)) # 열기준으로 덧셈

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


In [64]:
#2 mean : 평균
print(arr)
print(arr.mean())
print(arr.mean(axis=0)) # 행기준으로 평균
print(arr.mean(axis=1)) # 열기준으로 평균

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


In [67]:
#3 min, max : 최소값, 최대값
np.random.seed(123)
arr = np.random.permutation(np.arange(1,13)).reshape(3,4)
print(arr)
print(arr.min())
print(arr.min(axis=0)) # 행기준으로 최소값
print(arr.min(axis=1)) # 열기준으로 최소값

[[ 6  1  5 10]
 [ 9  8 11  4]
 [ 2  7 12  3]]
1
[2 1 5 3]
[1 4 2]


In [68]:
#4 var,std : 분산, 표준편차
arr = np.arange(1,13).reshape(3,4)
print(arr)
print(arr.var())
print(arr.var(axis=0)) # 행기준으로 분산
print(arr.var(axis=1)) # 열기준으로 분산
print(arr.std())
print(arr.std(axis=0)) # 행기준으로 표준편차
print(arr.std(axis=1)) # 열기준으로 표준편차

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11.916666666666666
[10.66666667 10.66666667 10.66666667 10.66666667]
[1.25 1.25 1.25]
3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


# **입출력**

1.  save
2.  load
3.  savez

In [91]:
#1. save
arr = np.arange(10)
np.save('test.npy',arr)

In [92]:
#2. load
arr = np.load('test.npy')
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
#3 savez : 다중 배열 저장
arr1 = np.arange(10)
arr2 = np.arange(10,20)

np.savez('test2', a1=arr1, a2=arr2)
loaded_arr = np.load('test2.npz')

print(loaded_arr['a1'])
print(loaded_arr['a2'])

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
